version: "3.8"
services:
  service-config:
    build: ./service-config
    image: gedeontiga/inf4057-service-config:latest
    ports:
      - "8888:8888"
    environment:
      - SPRING_APPLICATION_NAME=service-config
      - SPRING_CLOUD_CONFIG_SERVER_GIT_URI=https://github.com/gedeontiga/cloud-conf-inf4057
    networks:
      - microservices_network

  service-registry:
    build: ./service-registry
    image: gedeontiga/inf4057-service-registry:latest
    depends_on:
      - service-config
    ports:
      - "8761:8761"
    environment:
      - SPRING_APPLICATION_NAME=service-registry
      - SPRING_CLOUD_CONFIG_URI=http://service-config:8888
      - SPRING_CONFIG_IMPORT=configserver:http://service-config:8888
    networks:
      - microservices_network

  service-auth:
    build: ./service-auth
    image: gedeontiga/inf4057-service-auth:latest
    depends_on:
      - service-config
    ports:
      - "9090"
    environment:
      - SPRING_APPLICATION_NAME=service-auth
      - SPRING_CLOUD_CONFIG_URI=http://service-config:8888
      - SPRING_CONFIG_IMPORT=configserver:http://service-config:8888
    networks:
      - microservices_network

  service-user:
    build: ./service-user
    image: gedeontiga/inf4057-service-user:latest
    depends_on:
      - service-config
    ports:
      - "8081"
    environment:
      - SPRING_APPLICATION_NAME=service-user
      - SPRING_CLOUD_CONFIG_URI=http://service-config:8888
      - SPRING_CONFIG_IMPORT=configserver:http://service-config:8888
    networks:
      - microservices_network

  service-notif:
    build: ./service-notif
    image: gedeontiga/inf4057-service-notif:latest
    depends_on:
      - service-config
    ports:
      - "3025"
    environment:
      - SPRING_APPLICATION_NAME=service-notif
      - SPRING_CLOUD_CONFIG_URI=http://service-config:8888
      - SPRING_CONFIG_IMPORT=configserver:http://service-config:8888
    networks:
      - microservices_network

  service-agency:
    build: ./service-agency
    image: gedeontiga/inf4057-service-agency:latest
    depends_on:
      - service-config
    ports:
      - "8088"
    environment:
      - SPRING_APPLICATION_NAME=service-agency
      - SPRING_CLOUD_CONFIG_URI=http://service-config:8888
      - SPRING_CONFIG_IMPORT=configserver:http://service-config:8888
    networks:
      - microservices_network

  service-bank:
    build: ./service-bank
    image: gedeontiga/inf4057-service-bank:latest
    depends_on:
      - service-config
    ports:
      - "8088"
    environment:
      - SPRING_APPLICATION_NAME=service-bank
      - SPRING_CLOUD_CONFIG_URI=http://service-config:8888
      - SPRING_CONFIG_IMPORT=configserver:http://service-config:8888
    networks:
      - microservices_network

  service-deposit:
    build: ./service-deposit
    image: gedeontiga/inf4057-service-deposit:latest
    depends_on:
      - service-config
    ports:
      - "8088"
    environment:
      - SPRING_APPLICATION_NAME=service-deposit
      - SPRING_CLOUD_CONFIG_URI=http://service-config:8888
      - SPRING_CONFIG_IMPORT=configserver:http://service-config:8888
    networks:
      - microservices_network

  service-withdrawal:
    build: ./service-withdrawal
    image: gedeontiga/inf4057-service-withdrawal:latest
    depends_on:
      - service-config
    ports:
      - "8088"
    environment:
      - SPRING_APPLICATION_NAME=service-withdrawal
      - SPRING_CLOUD_CONFIG_URI=http://service-config:8888
      - SPRING_CONFIG_IMPORT=configserver:http://service-config:8888
    networks:
      - microservices_network

  service-transfer:
    build: ./service-transfer
    image: gedeontiga/inf4057-service-transfer:latest
    depends_on:
      - service-config
    ports:
      - "8088"
    environment:
      - SPRING_APPLICATION_NAME=service-transfer
      - SPRING_CLOUD_CONFIG_URI=http://service-config:8888
      - SPRING_CONFIG_IMPORT=configserver:http://service-config:8888
    networks:
      - microservices_network

  service-account:
    build: ./service-account
    image: gedeontiga/inf4057-service-account:latest
    depends_on:
      - service-config
    ports:
      - "8085"
    environment:
      - SPRING_APPLICATION_NAME=service-account
      - SPRING_CLOUD_CONFIG_URI=http://service-config:8888
      - SPRING_CONFIG_IMPORT=configserver:http://service-config:8888
    networks:
      - microservices_network

  service-proxy:
    build: ./service-proxy
    image: gedeontiga/inf4057-service-proxy:latest
    depends_on:
      - service-config
    ports:
      - "8075:8075"
    environment:
      - SPRING_APPLICATION_NAME=service-proxy
      - SPRING_CLOUD_CONFIG_URI=http://service-config:8888
      - SPRING_CONFIG_IMPORT=configserver:http://service-config:8888
    networks:
      - microservices_network

  mysql:
    image: mysql:latest
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
    networks:
      - microservices_network

  mongodb:
    image: mongo
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=gedeon
      - MONGO_INITDB_ROOT_PASSWORD=gedeon
    networks:
      - microservices_network

  rabbitmq:
    image: rabbitmq:4.0-management
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - microservices_network

networks:
  microservices_network:
    driver: bridge
