version: "3.8"
services:
  service-config:
    build:
      context: ./service-config
    ports:
      - "8888:8888"
    environment:
      - SPRING_APPLICATION_NAME=service-config
      - SPRING_CLOUD_CONFIG_SERVER_GIT_URI=https://github.com/gedeontiga/cloud-conf-inf4057
    networks:
      - microservices_network

  service-registry:
    build:
      context: ./service-registry
    depends_on:
      - service-config
    ports:
      - "8761:8761"
    environment:
      - SPRING_APPLICATION_NAME=service-registry
      - SPRING_CLOUD_CONFIG_URI=http://service-config:8888
      - SPRING_CONFIG_IMPORT=configserver:http://service-config:8888
    networks:
      - microservices_network

  service-notif:
    build:
      context: ./service-notif
    depends_on:
      - service-config
      - smtp4dev
    ports:
      - "3025"
    environment:
      - SPRING_APPLICATION_NAME=service-notif
      - SPRING_CLOUD_CONFIG_URI=http://service-config:8888
      - SPRING_CONFIG_IMPORT=configserver:http://service-config:8888
    networks:
      - microservices_network

  service-proxy:
    build:
      context: ./service-proxy
    depends_on:
      - service-config
      - service-registry
    ports:
      - "8075:8075"
    environment:
      - SPRING_APPLICATION_NAME=service-proxy
      - SPRING_CLOUD_CONFIG_URI=http://service-config:8888
      - SPRING_CONFIG_IMPORT=configserver:http://service-config:8888
    networks:
      - microservices_network

  service-bank:
    build:
      context: ./service-bank
    depends_on:
      - service-config
      - mongodb
      - service-proxy
    ports:
      - "8181:8181"
    environment:
      - SPRING_APPLICATION_NAME=service-bank
      - SPRING_CLOUD_CONFIG_URI=http://service-config:8888
      - SPRING_DATA_MONGODB_URI=mongodb://brunel:brunel@localhost:27017/service_bank?authSource=admin
      - SPRING_CONFIG_IMPORT=configserver:http://service-config:8888
    networks:
      - microservices_network

  service-deposit:
    build:
      context: ./service-deposit
    depends_on:
      - service-config
      - rabbitmq
      - mongodb
    ports:
      - "8183:8183"
    environment:
      - SPRING_APPLICATION_NAME=service-deposit
      - SPRING_CLOUD_CONFIG_URI=http://service-config:8888
      - SPRING_CONFIG_IMPORT=configserver:http://service-config:8888
    networks:
      - microservices_network

  service-withdrawal:
    build:
      context: ./service-withdrawal
    depends_on:
      - service-config
      - rabbitmq
      - mongodb
    ports:
      - "8184:8184"
    environment:
      - SPRING_APPLICATION_NAME=service-withdrawal
      - SPRING_CLOUD_CONFIG_URI=http://service-config:8888
      - SPRING_CONFIG_IMPORT=configserver:http://service-config:8888
    networks:
      - microservices_network

  service-transfer:
    build:
      context: ./service-transfer
    depends_on:
      - service-config
      - rabbitmq
      - mongodb
    ports:
      - "8185:8185"
    environment:
      - SPRING_APPLICATION_NAME=service-transfer
      - SPRING_CLOUD_CONFIG_URI=http://service-config:8888
      - SPRING_CONFIG_IMPORT=configserver:http://service-config:8888
    networks:
      - microservices_network

  mongodb:
    image: mongo
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=brunel
      - MONGO_INITDB_ROOT_PASSWORD=brunel
    networks:
      - microservices_network

  rabbitmq:
    image: rabbitmq:4.0-management
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - microservices_network

  smtp4dev:
    image: rnwood/smtp4dev
    ports:
      - "2525:25"
      - "30:80"
    networks:
      - microservices_network

networks:
  microservices_network:
    driver: bridge
