gateway.secret=${GATEWAY_SECRET}
spring.application.name=service-account
spring.activemq.broker-url=http://localhost:8888
spring.config.import=configserver:
logging.level.org.springframework.amqp=DEBUG
spring.rabbitmq.template.mandatory=true
