spring.application.name=service-config

# server.port=8080
server.port=8888

# spring.cloud.config.server.git.uri=file://${HOME}/cloud-conf-inf4057
spring.cloud.config.server.git.uri=https://github.com/gedeontiga/cloud-conf-inf4057