gateway.secret=${GATEWAY_SECRET}
spring.application.name=service-user
spring.cloud.config.uri=http://localhost:8888
spring.config.import=configserver:

# Users services port
# server.port=8082

# spring.h2.console.enabled=true
# spring.h2.console.path=/h2-console

# # JPA & H2 configuration
# spring.datasource.url=jdbc:h2:mem:testdb
# spring.datasource.driverClassName=org.h2.Driver
