spring.application.name=service-agency
spring.cloud.config.uri=http://localhost:8888
spring.config.import=configserver:
logging.level.org.springframework.amqp=DEBUG
spring.rabbitmq.template.mandatory=true
