version: '4'
services:
  service-bank:
    build: Dockerfile
    depends_on:
      - service-config
    ports:
      -"8181:8181"
    environment:
      - SPRING_APPLICATION_NAME=service-bank
      - SPRING_CLOUD_CONFIG_URI=http://service-config:8888 #Utilisation du nomde service
      - SPRING_CONFIG_IMPORT=configserver:http://service-config:8888
    networks:
      - microservices_network
  mongodb:
    image: mongodb:7.0.5
    container_name: mongodb
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME: root
      - MONGO_INITDB_ROOT_PASSWORD: password
      - MONGO_INITDB_DATABASE: service-bank
    volumes:
      - ./data:/data/db/
    networks:
      - microservices_network