spring.application.name=service-bank
spring.cloud.config.uri=http://localhost:8888
spring.config.import=configserver:

# Configuration variables
rabbitmq.queue.name=bankQueue
rabbitmq.exchange.name=requestExchange
rabbitmq.routing.key=requestExchange_bankQueue_key